name: CI
on:
   push: null
jobs:
   build-windows-vc2019:
      runs-on: windows-2019
      strategy:
        fail-fast: false
        matrix:
          build_type: ["Debug", "Release"]
      steps:
      -  uses: actions/checkout@v1
      -  name: Setup 
         shell: bash
         run: echo "BOOST_ROOT=$BOOST_ROOT_1_72_0" >> $GITHUB_ENV
      -  name: Compile
         run: |
            cd build
            cmake -G "Visual Studio 16 2019" ..
            cmake --build . --target install --config ${{ matrix.build_type }}
         shell: bash
      -  name: Test
         run: |
            cd build 
            ctest -C ${{ matrix.build_type }}
         shell: bash
         env:
            CTEST_OUTPUT_ON_FAILURE: 1
            VIRTUAL_ENV: VM