name: CI

on: 
  push:

jobs:
  build-windows-vc2019:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Setup Boost (Windows / Linux latest)
      shell: bash
      run: echo "BOOST_ROOT=$BOOST_ROOT_1_72_0" >> $GITHUB_ENV
    - name: Compile
      run: |
        cd build
        cmake -G "Visual Studio 16 2019" ..
        cmake --build . --target install --config Debug
      shell: bash
    - name: Test
      run: ctest -C Release
      shell: bash